name: CI

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'

      - name: Build JAR with Maven
        run: mvn clean install

      - name: Unzip Digital.zip
        run: unzip target/Digital.zip -d target

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}
          path: target/Digital
